# Implementación de una capa totalmente conectada

In [16]:
# importamos la librería.
import torch

In [17]:
# Creamos nuestra matriz X con los vectores de entrenamiento.

X = torch.arange(50, dtype=torch.float).view(10, 5)
# las funciones .view() y .reshape() son equivalentes.

X
# Mostramos la variable X.

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])

Lo que hace la función ```torch.arange()``` es crear un tensor unidimensional (vector).

Dentro de la función utilizando el número 50 ordenamos que el vector sea llenado con los números desde el 0 hasta el 49, luego especificamos el tipo de dato con ``` dtype=torch.float```.

Por último utilizamos la función ``` .view(10, 5) ``` para convertir este tensor unidimensional a un tensor bidimensional (matriz). Esto significa que tenemos 10 vectores de entrada con 5 componentes cada uno.






In [18]:
capa_densa = torch.nn.Linear(in_features=5,
                             out_features=3)

Creamos una variable llamada ``` capa_densa ```, esta va a ser nuestra capa totalmente conectada, para ello utilizamos la función ``` torch.nn.Linear() ```. Dentro de la función especificamos que la cantidad de datos de entrada serán 5 y la cantidad de datos de salida serán 3 usando ``` in_features=5 ``` y ``` out_features=3 ``` respectivamente.





In [19]:
capa_densa.weight

Parameter containing:
tensor([[ 0.2396,  0.1826, -0.0389,  0.0956,  0.0940],
        [ 0.1484, -0.0889, -0.3272,  0.3068,  0.1918],
        [-0.1055,  0.1080,  0.3224, -0.3643,  0.1064]], requires_grad=True)

utilizando la función ```.weight ``` mostramos el conjunto de pesos asociado a la capa densa. Esta es una matriz de tamaño 3×5 debido a la cantidad de neuronas de salida (3) y la cantidad de datos de entrada (5)

Todos estos valores son generados aleatoriamente al momento de construir la red neuronal.

In [20]:
capa_densa.bias

Parameter containing:
tensor([-0.1880, -0.1169,  0.3016], requires_grad=True)

utilizando la función ```.bias``` mostramos el conjunto de bias asociado a la capa densa. Este es un vector con 3 componentes debido a la cantidad de neuronas de salida (3)

In [21]:
# Introducimos la matriz de entrenamiento X a la capa densa y creamos una nueva variable que almacene los resultados.
salida = capa_densa(X)
print('resultados salida:\n', salida)
print('\nsalida dim:', salida.size())

resultados salida:
 tensor([[ 0.5796,  0.8273,  0.3868],
        [ 3.4444,  1.9816,  0.7213],
        [ 6.3091,  3.1359,  1.0559],
        [ 9.1739,  4.2901,  1.3904],
        [12.0386,  5.4444,  1.7249],
        [14.9034,  6.5987,  2.0594],
        [17.7681,  7.7529,  2.3939],
        [20.6329,  8.9072,  2.7284],
        [23.4977, 10.0615,  3.0629],
        [26.3624, 11.2157,  3.3975]], grad_fn=<AddmmBackward0>)

salida dim: torch.Size([10, 3])
